default: &default
  adapter: postgresql
  username: postgres_user
  password:
  host: ''

development:
  <<: *default
  database: qanda_development

test:
  <<: *default
  database: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 25 %>
